name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: /JW
          NEXT_PUBLIC_FIREBASE_API_KEY: AIzaSyAMXWaZS9YjcTXL0oGyhayKdD1EBBNukxU
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: jewelry-website-8f9e2.firebaseapp.com
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: jewelry-website-8f9e2
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: jewelry-website-8f9e2.firebasestorage.app
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "440556580032"
          NEXT_PUBLIC_FIREBASE_APP_ID: 1:440556580032:web:9cd7440712f6c907fa9125
          NEXT_PUBLIC_FIREBASE_DATABASE_URL: https://jewelry-website-8f9e2-default-rtdb.firebaseio.com/
          NEXT_PUBLIC_GITLAB_BASE_URL: https://gitlab.com
          NEXT_PUBLIC_GITLAB_ACCESS_TOKEN: ${{ secrets.NEXT_PUBLIC_GITLAB_ACCESS_TOKEN }}
          NEXT_PUBLIC_GITLAB_PROJECT_ID: "82976126"
          NEXT_PUBLIC_GITLAB_BRANCH: main
          NEXT_PUBLIC_GITLAB_UPLOAD_PATH: public/uploads

      - name: Add .nojekyll
        run: touch ./out/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
